In [87]:
import pandas as pd
import numpy as np
import seaborn as sm
import matplotlib.pyplot as plt

In [88]:
wc = pd.read_csv(r'C:\Users\Narasimha\yashdata\incomeasuption.csv')

In [89]:
wc.head()

    a   b          c       d     e   f  income
0  25   7    Private    Male     0  40       0
1  38   9    Private    Male     0  50       0
2  28  12  Local-gov    Male     0  40       1
3  44  10    Private    Male  7688  40       1
4  18  10          ?  Female     0  30       0

In [92]:
dummy_set=pd.get_dummies(wc.c)

In [93]:
dummy_set.head()

,?,Federal-gov,Local-gov,Never-worked,Private,Self-emp-inc,Self-emp-not-inc,State-gov,Without-pay
0,0,0,0,0,1,0,0,0,0
1,0,0,0,0,1,0,0,0,0
2,0,0,1,0,0,0,0,0,0
3,0,0,0,0,1,0,0,0,0
4,1,0,0,0,0,0,0,0,0

In [94]:
wc2=pd.concat([wc,dummy_set],axis=1)

In [95]:
wc2

,a,b,c,d,e,f,income,?,Federal-gov,Local-gov,Never-worked,Private,Self-emp-inc,Self-emp-not-inc,State-gov,Without-pay
0,25,7,Private,Male,0,40,0,0,0,0,0,1,0,0,0,0
1,38,9,Private,Male,0,50,0,0,0,0,0,1,0,0,0,0
2,28,12,Local-gov,Male,0,40,1,0,0,1,0,0,0,0,0,0
3,44,10,Private,Male,7688,40,1,0,0,0,0,1,0,0,0,0
4,18,10,?,Female,0,30,0,1,0,0,0,0,0,0,0,0
5,34,6,Private,Male,0,30,0,0,0,0,0,1,0,0,0,0
6,29,9,?,Male,0,40,0,1,0,0,0,0,0,0,0,0
7,63,15,Self-emp-not-inc,Male,3103,32,1,0,0,0,0,0,0,1,0,0
8,24,10,Private,Female,0,40,0,0,0,0,0,1,0,0,0,0
9,55,4,Private,Male,0,10,0,0,0,0,0,1,0,0,0,0
10,65,9,Private,Male,6418,40,1,0,0,0,0,1,0,0,0,0
11,36,13,Federal-gov,Male,0,40,0,0,1,0,0,0,0,0,0,0
12,26,9,Private,Female,0,39,0,0,0,0,0,1,0,0,0,0
13,58,9,?,Male,0,35,0,1,0,0,0,0,0,0,0,0
14,48,9,Private,Male,3103,48,1,0,0,0,0,1,0,0,0,0
15,43,14,Private,Male,0,50,1,0,0,0,0,1,0,0,0,0
16,20,10,State-gov,Male,0,25,0,0,0,0,0,0,0,0,1,0
17,43,9,Private,Female,0,30,0,0,0,0,0,1,0,0,0,0
18,37,9,Private,Female,0,20,0,0,0,0,0,1,0,0,0,0
19,40,16,Private,Male,0,45,1,0,0,0,0,1,0,0,0,0
20,34,13,Private,Male,0,47,1,0,0,0,0,1,0,0,0,0
21,34,10,Private,Female,0,35,0,0,0,0,0,1,0,0,0,0
22,72,4,?,Female,0,6,0,1,0,0,0,0,0,0,0,0
23,25,13,Private,Male,0,43,0,0,0,0,0,1,0,0,0,0
24,25,13,Private,Male,0,40,0,0,0,0,0,1,0,0,0,0
25,45,9,Self-emp-not-inc,Male,7298,90,1,0,0,0,0,0,0,1,0,0
26,22,9,Private,Male,0,20,0,0,0,0,0,1,0,0,0,0
27,23,9,Private,Male,0,54,0,0,0,0,0,1,0,0,0,0
28,54,9,Private,Male,0,35,0,0,0,0,0,1,0,0,0,0
29,32,10,Self-emp-not-inc,Male,0,60,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48812,30,13,?,Female,0,99,0,1,0,0,0,0,0,0,0,0
48813,34,16,Private,Male,0,60,1,0,0,0,0,1,0,0,0,0
48814,54,13,Private,Male,0,50,1,0,0,0,0,1,0,0,0,0
48815,37,10,Private,Female,0,39,0,0,0,0,0,1,0,0,0,0
48816,22,8,Private,Male,0,35,0,0,0,0,0,1,0,0,0,0
48817,34,13,Private,Female,0,55,1,0,0,0,0,1,0,0,0,0
48818,30,9,Private,Male,0,46,0,0,0,0,0,1,0,0,0,0
48819,38,13,Private,Female,15020,45,1,0,0,0,0,1,0,0,0,0
48820,71,16,?,Male,0,10,1,1,0,0,0,0,0,0,0,0
48821,45,9,State-gov,Female,0,40,0,0,0,0,0,0,0,0,1,0
48822,41,9,?,Female,0,32,0,1,0,0,0,0,0,0,0,0
48823,72,9,?,Male,0,25,0,1,0,0,0,0,0,0,0,0
48824,45,12,Local-gov,Female,0,48,0,0,0,1,0,0,0,0,0,0
48825,31,14,Private,Female,0,30,0,0,0,0,0,1,0,0,0,0
48826,39,12,Local-gov,Female,0,20,1,0,0,1,0,0,0,0,0,0
48827,37,12,Private,Female,0,40,0,0,0,0,0,1,0,0,0,0
48828,43,9,Private,Male,0,40,0,0,0,0,0,1,0,0,0,0
48829,65,15,Self-emp-not-inc,Male,1086,60,0,0,0,0,0,0,0,1,0,0
48830,43,10,State-gov,Female,0,40,0,0,0,0,0,0,0,0,1,0
48831,43,10,Self-emp-not-inc,Male,0,50,0,0,0,0,0,0,0,1,0,0
48832,32,6,Private,Male,0,40,0,0,0,0,0,1,0,0,0,0
48833,43,11,Private,Male,0,45,0,0,0,0,0,1,0,0,0,0
48834,32,14,Private,Male,0,11,0,0,0,0,0,1,0,0,0,0
48835,53,14,Private,Male,0,40,1,0,0,0,0,1,0,0,0,0
48836,22,10,Private,Male,0,40,0,0,0,0,0,1,0,0,0,0
48837,27,12,Private,Female,0,38,0,0,0,0,0,1,0,0,0,0
48838,40,9,Private,Male,0,40,1,0,0,0,0,1,0,0,0,0
48839,58,9,Private,Female,0,40,0,0,0,0,0,1,0,0,0,0
48840,22,9,Private,Male,0,20,0,0,0,0,0,1,0,0,0,0
48841,52,9,Self-emp-inc,Female,15024,40,1,0,0,0,0,0,1,0,0,0

In [96]:
pd.get_dummies(wc2,columns=['c'], drop_first=True)

,a,b,d,e,f,income,?,Federal-gov,Local-gov,Never-worked,...,State-gov,Without-pay,c_Federal-gov,c_Local-gov,c_Never-worked,c_Private,c_Self-emp-inc,c_Self-emp-not-inc,c_State-gov,c_Without-pay
0,25,7,Male,0,40,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1,38,9,Male,0,50,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,28,12,Male,0,40,1,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
3,44,10,Male,7688,40,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
4,18,10,Female,0,30,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,34,6,Male,0,30,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
6,29,9,Male,0,40,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,63,15,Male,3103,32,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
8,24,10,Female,0,40,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
9,55,4,Male,0,10,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
10,65,9,Male,6418,40,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
11,36,13,Male,0,40,0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,0
12,26,9,Female,0,39,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
13,58,9,Male,0,35,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,48,9,Male,3103,48,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
15,43,14,Male,0,50,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
16,20,10,Male,0,25,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
17,43,9,Female,0,30,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
18,37,9,Female,0,20,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
19,40,16,Male,0,45,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
20,34,13,Male,0,47,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
21,34,10,Female,0,35,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
22,72,4,Female,0,6,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,25,13,Male,0,43,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
24,25,13,Male,0,40,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
25,45,9,Male,7298,90,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
26,22,9,Male,0,20,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
27,23,9,Male,0,54,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
28,54,9,Male,0,35,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
29,32,10,Male,0,60,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48812,30,13,Female,0,99,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
48813,34,16,Male,0,60,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
48814,54,13,Male,0,50,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
48815,37,10,Female,0,39,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
48816,22,8,Male,0,35,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
48817,34,13,Female,0,55,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
48818,30,9,Male,0,46,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
48819,38,13,Female,15020,45,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
48820,71,16,Male,0,10,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
48821,45,9,Female,0,40,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
48822,41,9,Female,0,32,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
48823,72,9,Male,0,25,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
48824,45,12,Female,0,48,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
48825,31,14,Female,0,30,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
48826,39,12,Female,0,20,1,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
48827,37,12,Female,0,40,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
48828,43,9,Male,0,40,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
48829,65,15,Male,1086,60,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
48830,43,10,Female,0,40,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
48831,43,10,Male,0,50,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
48832,32,6,Male,0,40,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
48833,43,11,Male,0,45,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
48834,32,14,Male,0,11,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
48835,53,14,Male,0,40,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
48836,22,10,Male,0,40,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
48837,27,12,Female,0,38,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
48838,40,9,Male,0,40,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
48839,58,9,Female,0,40,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
48840,22,9,Male,0,20,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
48841,52,9,Female,15024,40,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [97]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()
x = ohe.fit_transform(wc2.iloc[:,6:15]).toarray()

C:\Users\Narasimha\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)

In [98]:
x

array([[1., 0., 1., ..., 0., 1., 0.],
       [1., 0., 1., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       ...,
       [1., 0., 1., ..., 0., 1., 0.],
       [1., 0., 1., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.]])

In [99]:
x=pd.DataFrame(x)
x

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
1,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
2,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
3,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
4,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
5,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
6,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
7,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
8,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
9,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
10,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
11,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
12,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
13,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
14,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
15,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
16,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
17,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
18,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
19,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
20,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
21,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
22,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
23,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
24,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
25,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
26,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
27,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
28,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
29,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48812,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
48813,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
48814,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
48815,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
48816,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
48817,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
48818,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
48819,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
48820,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
48821,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
48822,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
48823,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
48824,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
48825,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
48826,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
48827,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
48828,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
48829,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
48830,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
48831,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
48832,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
48833,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
48834,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
48835,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
48836,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
48837,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
48838,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
48839,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
48840,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
48841,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0

In [102]:
wc1=wc2.drop(['d'],axis=1)

In [103]:
wc1

,a,b,c,e,f,income,?,Federal-gov,Local-gov,Never-worked,Private,Self-emp-inc,Self-emp-not-inc,State-gov,Without-pay
0,25,7,Private,0,40,0,0,0,0,0,1,0,0,0,0
1,38,9,Private,0,50,0,0,0,0,0,1,0,0,0,0
2,28,12,Local-gov,0,40,1,0,0,1,0,0,0,0,0,0
3,44,10,Private,7688,40,1,0,0,0,0,1,0,0,0,0
4,18,10,?,0,30,0,1,0,0,0,0,0,0,0,0
5,34,6,Private,0,30,0,0,0,0,0,1,0,0,0,0
6,29,9,?,0,40,0,1,0,0,0,0,0,0,0,0
7,63,15,Self-emp-not-inc,3103,32,1,0,0,0,0,0,0,1,0,0
8,24,10,Private,0,40,0,0,0,0,0,1,0,0,0,0
9,55,4,Private,0,10,0,0,0,0,0,1,0,0,0,0
10,65,9,Private,6418,40,1,0,0,0,0,1,0,0,0,0
11,36,13,Federal-gov,0,40,0,0,1,0,0,0,0,0,0,0
12,26,9,Private,0,39,0,0,0,0,0,1,0,0,0,0
13,58,9,?,0,35,0,1,0,0,0,0,0,0,0,0
14,48,9,Private,3103,48,1,0,0,0,0,1,0,0,0,0
15,43,14,Private,0,50,1,0,0,0,0,1,0,0,0,0
16,20,10,State-gov,0,25,0,0,0,0,0,0,0,0,1,0
17,43,9,Private,0,30,0,0,0,0,0,1,0,0,0,0
18,37,9,Private,0,20,0,0,0,0,0,1,0,0,0,0
19,40,16,Private,0,45,1,0,0,0,0,1,0,0,0,0
20,34,13,Private,0,47,1,0,0,0,0,1,0,0,0,0
21,34,10,Private,0,35,0,0,0,0,0,1,0,0,0,0
22,72,4,?,0,6,0,1,0,0,0,0,0,0,0,0
23,25,13,Private,0,43,0,0,0,0,0,1,0,0,0,0
24,25,13,Private,0,40,0,0,0,0,0,1,0,0,0,0
25,45,9,Self-emp-not-inc,7298,90,1,0,0,0,0,0,0,1,0,0
26,22,9,Private,0,20,0,0,0,0,0,1,0,0,0,0
27,23,9,Private,0,54,0,0,0,0,0,1,0,0,0,0
28,54,9,Private,0,35,0,0,0,0,0,1,0,0,0,0
29,32,10,Self-emp-not-inc,0,60,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48812,30,13,?,0,99,0,1,0,0,0,0,0,0,0,0
48813,34,16,Private,0,60,1,0,0,0,0,1,0,0,0,0
48814,54,13,Private,0,50,1,0,0,0,0,1,0,0,0,0
48815,37,10,Private,0,39,0,0,0,0,0,1,0,0,0,0
48816,22,8,Private,0,35,0,0,0,0,0,1,0,0,0,0
48817,34,13,Private,0,55,1,0,0,0,0,1,0,0,0,0
48818,30,9,Private,0,46,0,0,0,0,0,1,0,0,0,0
48819,38,13,Private,15020,45,1,0,0,0,0,1,0,0,0,0
48820,71,16,?,0,10,1,1,0,0,0,0,0,0,0,0
48821,45,9,State-gov,0,40,0,0,0,0,0,0,0,0,1,0
48822,41,9,?,0,32,0,1,0,0,0,0,0,0,0,0
48823,72,9,?,0,25,0,1,0,0,0,0,0,0,0,0
48824,45,12,Local-gov,0,48,0,0,0,1,0,0,0,0,0,0
48825,31,14,Private,0,30,0,0,0,0,0,1,0,0,0,0
48826,39,12,Local-gov,0,20,1,0,0,1,0,0,0,0,0,0
48827,37,12,Private,0,40,0,0,0,0,0,1,0,0,0,0
48828,43,9,Private,0,40,0,0,0,0,0,1,0,0,0,0
48829,65,15,Self-emp-not-inc,1086,60,0,0,0,0,0,0,0,1,0,0
48830,43,10,State-gov,0,40,0,0,0,0,0,0,0,0,1,0
48831,43,10,Self-emp-not-inc,0,50,0,0,0,0,0,0,0,1,0,0
48832,32,6,Private,0,40,0,0,0,0,0,1,0,0,0,0
48833,43,11,Private,0,45,0,0,0,0,0,1,0,0,0,0
48834,32,14,Private,0,11,0,0,0,0,0,1,0,0,0,0
48835,53,14,Private,0,40,1,0,0,0,0,1,0,0,0,0
48836,22,10,Private,0,40,0,0,0,0,0,1,0,0,0,0
48837,27,12,Private,0,38,0,0,0,0,0,1,0,0,0,0
48838,40,9,Private,0,40,1,0,0,0,0,1,0,0,0,0
48839,58,9,Private,0,40,0,0,0,0,0,1,0,0,0,0
48840,22,9,Private,0,20,0,0,0,0,0,1,0,0,0,0
48841,52,9,Self-emp-inc,15024,40,1,0,0,0,0,0,1,0,0,0

In [104]:
wc1=wc1.drop(['c'],axis=1)

In [105]:
wc1

,a,b,e,f,income,?,Federal-gov,Local-gov,Never-worked,Private,Self-emp-inc,Self-emp-not-inc,State-gov,Without-pay
0,25,7,0,40,0,0,0,0,0,1,0,0,0,0
1,38,9,0,50,0,0,0,0,0,1,0,0,0,0
2,28,12,0,40,1,0,0,1,0,0,0,0,0,0
3,44,10,7688,40,1,0,0,0,0,1,0,0,0,0
4,18,10,0,30,0,1,0,0,0,0,0,0,0,0
5,34,6,0,30,0,0,0,0,0,1,0,0,0,0
6,29,9,0,40,0,1,0,0,0,0,0,0,0,0
7,63,15,3103,32,1,0,0,0,0,0,0,1,0,0
8,24,10,0,40,0,0,0,0,0,1,0,0,0,0
9,55,4,0,10,0,0,0,0,0,1,0,0,0,0
10,65,9,6418,40,1,0,0,0,0,1,0,0,0,0
11,36,13,0,40,0,0,1,0,0,0,0,0,0,0
12,26,9,0,39,0,0,0,0,0,1,0,0,0,0
13,58,9,0,35,0,1,0,0,0,0,0,0,0,0
14,48,9,3103,48,1,0,0,0,0,1,0,0,0,0
15,43,14,0,50,1,0,0,0,0,1,0,0,0,0
16,20,10,0,25,0,0,0,0,0,0,0,0,1,0
17,43,9,0,30,0,0,0,0,0,1,0,0,0,0
18,37,9,0,20,0,0,0,0,0,1,0,0,0,0
19,40,16,0,45,1,0,0,0,0,1,0,0,0,0
20,34,13,0,47,1,0,0,0,0,1,0,0,0,0
21,34,10,0,35,0,0,0,0,0,1,0,0,0,0
22,72,4,0,6,0,1,0,0,0,0,0,0,0,0
23,25,13,0,43,0,0,0,0,0,1,0,0,0,0
24,25,13,0,40,0,0,0,0,0,1,0,0,0,0
25,45,9,7298,90,1,0,0,0,0,0,0,1,0,0
26,22,9,0,20,0,0,0,0,0,1,0,0,0,0
27,23,9,0,54,0,0,0,0,0,1,0,0,0,0
28,54,9,0,35,0,0,0,0,0,1,0,0,0,0
29,32,10,0,60,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48812,30,13,0,99,0,1,0,0,0,0,0,0,0,0
48813,34,16,0,60,1,0,0,0,0,1,0,0,0,0
48814,54,13,0,50,1,0,0,0,0,1,0,0,0,0
48815,37,10,0,39,0,0,0,0,0,1,0,0,0,0
48816,22,8,0,35,0,0,0,0,0,1,0,0,0,0
48817,34,13,0,55,1,0,0,0,0,1,0,0,0,0
48818,30,9,0,46,0,0,0,0,0,1,0,0,0,0
48819,38,13,15020,45,1,0,0,0,0,1,0,0,0,0
48820,71,16,0,10,1,1,0,0,0,0,0,0,0,0
48821,45,9,0,40,0,0,0,0,0,0,0,0,1,0
48822,41,9,0,32,0,1,0,0,0,0,0,0,0,0
48823,72,9,0,25,0,1,0,0,0,0,0,0,0,0
48824,45,12,0,48,0,0,0,1,0,0,0,0,0,0
48825,31,14,0,30,0,0,0,0,0,1,0,0,0,0
48826,39,12,0,20,1,0,0,1,0,0,0,0,0,0
48827,37,12,0,40,0,0,0,0,0,1,0,0,0,0
48828,43,9,0,40,0,0,0,0,0,1,0,0,0,0
48829,65,15,1086,60,0,0,0,0,0,0,0,1,0,0
48830,43,10,0,40,0,0,0,0,0,0,0,0,1,0
48831,43,10,0,50,0,0,0,0,0,0,0,1,0,0
48832,32,6,0,40,0,0,0,0,0,1,0,0,0,0
48833,43,11,0,45,0,0,0,0,0,1,0,0,0,0
48834,32,14,0,11,0,0,0,0,0,1,0,0,0,0
48835,53,14,0,40,1,0,0,0,0,1,0,0,0,0
48836,22,10,0,40,0,0,0,0,0,1,0,0,0,0
48837,27,12,0,38,0,0,0,0,0,1,0,0,0,0
48838,40,9,0,40,1,0,0,0,0,1,0,0,0,0
48839,58,9,0,40,0,0,0,0,0,1,0,0,0,0
48840,22,9,0,20,0,0,0,0,0,1,0,0,0,0
48841,52,9,15024,40,1,0,0,0,0,0,1,0,0,0

In [106]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()
x = ohe.fit_transform(wc1.iloc[:,5:15]).toarray()

C:\Users\Narasimha\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)

In [107]:
x

array([[1., 0., 1., ..., 0., 1., 0.],
       [1., 0., 1., ..., 0., 1., 0.],
       [1., 0., 1., ..., 0., 1., 0.],
       ...,
       [1., 0., 1., ..., 0., 1., 0.],
       [1., 0., 1., ..., 0., 1., 0.],
       [1., 0., 1., ..., 0., 1., 0.]])

In [108]:
x=pd.DataFrame(x)

In [109]:
x

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
1,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
2,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
3,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
4,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
5,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
6,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
7,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
8,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
9,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
10,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
11,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
12,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
13,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
14,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
15,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
16,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
17,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
18,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
19,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
20,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
21,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
22,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
23,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
24,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
25,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
26,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
27,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
28,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
29,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48812,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
48813,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
48814,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
48815,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
48816,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
48817,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
48818,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
48819,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
48820,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
48821,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
48822,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
48823,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
48824,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
48825,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
48826,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
48827,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
48828,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
48829,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
48830,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
48831,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
48832,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
48833,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
48834,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
48835,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
48836,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
48837,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
48838,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
48839,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
48840,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
48841,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0

In [110]:
data=wc1.drop(wc1.iloc[:,5:15],axis=1)

In [111]:
data

        a   b      e   f  income
0      25   7      0  40       0
1      38   9      0  50       0
2      28  12      0  40       1
3      44  10   7688  40       1
4      18  10      0  30       0
5      34   6      0  30       0
6      29   9      0  40       0
7      63  15   3103  32       1
8      24  10      0  40       0
9      55   4      0  10       0
10     65   9   6418  40       1
11     36  13      0  40       0
12     26   9      0  39       0
13     58   9      0  35       0
14     48   9   3103  48       1
15     43  14      0  50       1
16     20  10      0  25       0
17     43   9      0  30       0
18     37   9      0  20       0
19     40  16      0  45       1
20     34  13      0  47       1
21     34  10      0  35       0
22     72   4      0   6       0
23     25  13      0  43       0
24     25  13      0  40       0
25     45   9   7298  90       1
26     22   9      0  20       0
27     23   9      0  54       0
28     54   9      0  35       0
29     32  10      0  60       0
...    ..  ..    ...  ..     ...
48812  30  13      0  99       0
48813  34  16      0  60       1
48814  54  13      0  50       1
48815  37  10      0  39       0
48816  22   8      0  35       0
48817  34  13      0  55       1
48818  30   9      0  46       0
48819  38  13  15020  45       1
48820  71  16      0  10       1
48821  45   9      0  40       0
48822  41   9      0  32       0
48823  72   9      0  25       0
48824  45  12      0  48       0
48825  31  14      0  30       0
48826  39  12      0  20       1
48827  37  12      0  40       0
48828  43   9      0  40       0
48829  65  15   1086  60       0
48830  43  10      0  40       0
48831  43  10      0  50       0
48832  32   6      0  40       0
48833  43  11      0  45       0
48834  32  14      0  11       0
48835  53  14      0  40       1
48836  22  10      0  40       0
48837  27  12      0  38       0
48838  40   9      0  40       1
48839  58   9      0  40       0
48840  22   9      0  20       0
48841  52   9  15024  40       1

[48842 rows x 5 columns]

In [112]:
newdata=pd.concat([data,x],axis=1)

In [113]:
newdata.head()

,a,b,e,f,income,0,1,2,3,4,...,8,9,10,11,12,13,14,15,16,17
0,25,7,0,40,0,1.0,0.0,1.0,0.0,1.0,...,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
1,38,9,0,50,0,1.0,0.0,1.0,0.0,1.0,...,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
2,28,12,0,40,1,1.0,0.0,1.0,0.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
3,44,10,7688,40,1,1.0,0.0,1.0,0.0,1.0,...,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
4,18,10,0,30,0,0.0,1.0,1.0,0.0,1.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0

In [114]:
data.head()

    a   b     e   f  income
0  25   7     0  40       0
1  38   9     0  50       0
2  28  12     0  40       1
3  44  10  7688  40       1
4  18  10     0  30       0

In [115]:
data.describe()

                  a             b             e             f        income
count  48842.000000  48842.000000  48842.000000  48842.000000  48842.000000
mean      38.643585     10.078089   1079.067626     40.422382      0.239282
std       13.710510      2.570973   7452.019058     12.391444      0.426649
min       17.000000      1.000000      0.000000      1.000000      0.000000
25%       28.000000      9.000000      0.000000     40.000000      0.000000
50%       37.000000     10.000000      0.000000     40.000000      0.000000
75%       48.000000     12.000000      0.000000     45.000000      0.000000
max       90.000000     16.000000  99999.000000     99.000000      1.000000

In [116]:
data.isnull().sum()

a         0
b         0
e         0
f         0
income    0
dtype: int64

In [117]:
import statsmodels.formula.api as smf
a=smf.logit('income ~ a+b+e+f',data).fit()
a.summary()

Optimization terminated successfully.
         Current function value: 0.414008
         Iterations 8

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                 income   No. Observations:                48842
Model:                          Logit   Df Residuals:                    48837
Method:                           MLE   Df Model:                            4
Date:                Tue, 13 Aug 2019   Pseudo R-squ.:                  0.2476
Time:                        20:26:41   Log-Likelihood:                -20221.
converged:                       True   LL-Null:                       -26875.
Covariance Type:            nonrobust   LLR p-value:                     0.000
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -8.3175      0.093    -89.402      0.000      -8.500      -8.135
a              0.0431      0.001     43.915      0.000       0.041       0.045
b              0.3295      0.006     59.816      0.000       0.319       0.340
e              0.0003   7.89e-06     38.954      0.000       0.000       0.000
f              0.0408      0.001     38.481      0.000       0.039       0.043
==============================================================================
"""

In [118]:
y_pred=a.predict(data)

In [119]:
y_pred

0        0.035566
1        0.158076
2        0.178989
3        0.704548
4        0.046464
5        0.025324
6        0.078079
7        0.832005
8        0.086700
9        0.014465
10       0.741551
11       0.299638
12       0.066681
13       0.194104
14       0.408511
15       0.547476
16       0.041506
17       0.093301
18       0.050170
19       0.626239
20       0.343145
21       0.106406
22       0.025273
23       0.231403
24       0.210333
25       0.924472
26       0.026933
27       0.103819
28       0.168557
29       0.232690
           ...
48812    0.786169
48813    0.704789
48814    0.582937
48815    0.137598
48816    0.035433
48817    0.420042
48818    0.101504
48819    0.982977
48820    0.604031
48821    0.144373
48822    0.092922
48823    0.226391
48824    0.386012
48825    0.241718
48826    0.133995
48827    0.243152
48828    0.134052
48829    0.901132
48830    0.177109
48831    0.244591
48832    0.034619
48833    0.268484
48834    0.132833
48835    0.553027
48836    0.080116
48837    0.161383
48838    0.119746
48839    0.228048
48840    0.026933
48841    0.958435
Length: 48842, dtype: float64

In [120]:
data['prob']=y_pred

In [121]:
data

        a   b      e   f  income      prob
0      25   7      0  40       0  0.035566
1      38   9      0  50       0  0.158076
2      28  12      0  40       1  0.178989
3      44  10   7688  40       1  0.704548
4      18  10      0  30       0  0.046464
5      34   6      0  30       0  0.025324
6      29   9      0  40       0  0.078079
7      63  15   3103  32       1  0.832005
8      24  10      0  40       0  0.086700
9      55   4      0  10       0  0.014465
10     65   9   6418  40       1  0.741551
11     36  13      0  40       0  0.299638
12     26   9      0  39       0  0.066681
13     58   9      0  35       0  0.194104
14     48   9   3103  48       1  0.408511
15     43  14      0  50       1  0.547476
16     20  10      0  25       0  0.041506
17     43   9      0  30       0  0.093301
18     37   9      0  20       0  0.050170
19     40  16      0  45       1  0.626239
20     34  13      0  47       1  0.343145
21     34  10      0  35       0  0.106406
22     72   4      0   6       0  0.025273
23     25  13      0  43       0  0.231403
24     25  13      0  40       0  0.210333
25     45   9   7298  90       1  0.924472
26     22   9      0  20       0  0.026933
27     23   9      0  54       0  0.103819
28     54   9      0  35       0  0.168557
29     32  10      0  60       0  0.232690
...    ..  ..    ...  ..     ...       ...
48812  30  13      0  99       0  0.786169
48813  34  16      0  60       1  0.704789
48814  54  13      0  50       1  0.582937
48815  37  10      0  39       0  0.137598
48816  22   8      0  35       0  0.035433
48817  34  13      0  55       1  0.420042
48818  30   9      0  46       0  0.101504
48819  38  13  15020  45       1  0.982977
48820  71  16      0  10       1  0.604031
48821  45   9      0  40       0  0.144373
48822  41   9      0  32       0  0.092922
48823  72   9      0  25       0  0.226391
48824  45  12      0  48       0  0.386012
48825  31  14      0  30       0  0.241718
48826  39  12      0  20       1  0.133995
48827  37  12      0  40       0  0.243152
48828  43   9      0  40       0  0.134052
48829  65  15   1086  60       0  0.901132
48830  43  10      0  40       0  0.177109
48831  43  10      0  50       0  0.244591
48832  32   6      0  40       0  0.034619
48833  43  11      0  45       0  0.268484
48834  32  14      0  11       0  0.132833
48835  53  14      0  40       1  0.553027
48836  22  10      0  40       0  0.080116
48837  27  12      0  38       0  0.161383
48838  40   9      0  40       1  0.119746
48839  58   9      0  40       0  0.228048
48840  22   9      0  20       0  0.026933
48841  52   9  15024  40       1  0.958435

[48842 rows x 6 columns]

In [122]:
data['pvalues']=0

In [123]:
data

        a   b      e   f  income      prob  pvalues
0      25   7      0  40       0  0.035566        0
1      38   9      0  50       0  0.158076        0
2      28  12      0  40       1  0.178989        0
3      44  10   7688  40       1  0.704548        0
4      18  10      0  30       0  0.046464        0
5      34   6      0  30       0  0.025324        0
6      29   9      0  40       0  0.078079        0
7      63  15   3103  32       1  0.832005        0
8      24  10      0  40       0  0.086700        0
9      55   4      0  10       0  0.014465        0
10     65   9   6418  40       1  0.741551        0
11     36  13      0  40       0  0.299638        0
12     26   9      0  39       0  0.066681        0
13     58   9      0  35       0  0.194104        0
14     48   9   3103  48       1  0.408511        0
15     43  14      0  50       1  0.547476        0
16     20  10      0  25       0  0.041506        0
17     43   9      0  30       0  0.093301        0
18     37   9      0  20       0  0.050170        0
19     40  16      0  45       1  0.626239        0
20     34  13      0  47       1  0.343145        0
21     34  10      0  35       0  0.106406        0
22     72   4      0   6       0  0.025273        0
23     25  13      0  43       0  0.231403        0
24     25  13      0  40       0  0.210333        0
25     45   9   7298  90       1  0.924472        0
26     22   9      0  20       0  0.026933        0
27     23   9      0  54       0  0.103819        0
28     54   9      0  35       0  0.168557        0
29     32  10      0  60       0  0.232690        0
...    ..  ..    ...  ..     ...       ...      ...
48812  30  13      0  99       0  0.786169        0
48813  34  16      0  60       1  0.704789        0
48814  54  13      0  50       1  0.582937        0
48815  37  10      0  39       0  0.137598        0
48816  22   8      0  35       0  0.035433        0
48817  34  13      0  55       1  0.420042        0
48818  30   9      0  46       0  0.101504        0
48819  38  13  15020  45       1  0.982977        0
48820  71  16      0  10       1  0.604031        0
48821  45   9      0  40       0  0.144373        0
48822  41   9      0  32       0  0.092922        0
48823  72   9      0  25       0  0.226391        0
48824  45  12      0  48       0  0.386012        0
48825  31  14      0  30       0  0.241718        0
48826  39  12      0  20       1  0.133995        0
48827  37  12      0  40       0  0.243152        0
48828  43   9      0  40       0  0.134052        0
48829  65  15   1086  60       0  0.901132        0
48830  43  10      0  40       0  0.177109        0
48831  43  10      0  50       0  0.244591        0
48832  32   6      0  40       0  0.034619        0
48833  43  11      0  45       0  0.268484        0
48834  32  14      0  11       0  0.132833        0
48835  53  14      0  40       1  0.553027        0
48836  22  10      0  40       0  0.080116        0
48837  27  12      0  38       0  0.161383        0
48838  40   9      0  40       1  0.119746        0
48839  58   9      0  40       0  0.228048        0
48840  22   9      0  20       0  0.026933        0
48841  52   9  15024  40       1  0.958435        0

[48842 rows x 7 columns]

In [133]:
data.loc[data.prob >= 0.5,"pvalues"] = True

In [134]:
data

        a   b      e   f  income      prob pvalues PValue
0      25   7      0  40       0  0.035566       0    NaN
1      38   9      0  50       0  0.158076       0    NaN
2      28  12      0  40       1  0.178989       0    NaN
3      44  10   7688  40       1  0.704548    True   True
4      18  10      0  30       0  0.046464       0    NaN
5      34   6      0  30       0  0.025324       0    NaN
6      29   9      0  40       0  0.078079       0    NaN
7      63  15   3103  32       1  0.832005    True   True
8      24  10      0  40       0  0.086700       0    NaN
9      55   4      0  10       0  0.014465       0    NaN
10     65   9   6418  40       1  0.741551    True   True
11     36  13      0  40       0  0.299638       0    NaN
12     26   9      0  39       0  0.066681       0    NaN
13     58   9      0  35       0  0.194104       0    NaN
14     48   9   3103  48       1  0.408511       0    NaN
15     43  14      0  50       1  0.547476    True   True
16     20  10      0  25       0  0.041506       0    NaN
17     43   9      0  30       0  0.093301       0    NaN
18     37   9      0  20       0  0.050170       0    NaN
19     40  16      0  45       1  0.626239    True   True
20     34  13      0  47       1  0.343145       0    NaN
21     34  10      0  35       0  0.106406       0    NaN
22     72   4      0   6       0  0.025273       0    NaN
23     25  13      0  43       0  0.231403       0    NaN
24     25  13      0  40       0  0.210333       0    NaN
25     45   9   7298  90       1  0.924472    True   True
26     22   9      0  20       0  0.026933       0    NaN
27     23   9      0  54       0  0.103819       0    NaN
28     54   9      0  35       0  0.168557       0    NaN
29     32  10      0  60       0  0.232690       0    NaN
...    ..  ..    ...  ..     ...       ...     ...    ...
48812  30  13      0  99       0  0.786169    True   True
48813  34  16      0  60       1  0.704789    True   True
48814  54  13      0  50       1  0.582937    True   True
48815  37  10      0  39       0  0.137598       0    NaN
48816  22   8      0  35       0  0.035433       0    NaN
48817  34  13      0  55       1  0.420042       0    NaN
48818  30   9      0  46       0  0.101504       0    NaN
48819  38  13  15020  45       1  0.982977    True   True
48820  71  16      0  10       1  0.604031    True   True
48821  45   9      0  40       0  0.144373       0    NaN
48822  41   9      0  32       0  0.092922       0    NaN
48823  72   9      0  25       0  0.226391       0    NaN
48824  45  12      0  48       0  0.386012       0    NaN
48825  31  14      0  30       0  0.241718       0    NaN
48826  39  12      0  20       1  0.133995       0    NaN
48827  37  12      0  40       0  0.243152       0    NaN
48828  43   9      0  40       0  0.134052       0    NaN
48829  65  15   1086  60       0  0.901132    True   True
48830  43  10      0  40       0  0.177109       0    NaN
48831  43  10      0  50       0  0.244591       0    NaN
48832  32   6      0  40       0  0.034619       0    NaN
48833  43  11      0  45       0  0.268484       0    NaN
48834  32  14      0  11       0  0.132833       0    NaN
48835  53  14      0  40       1  0.553027    True   True
48836  22  10      0  40       0  0.080116       0    NaN
48837  27  12      0  38       0  0.161383       0    NaN
48838  40   9      0  40       1  0.119746       0    NaN
48839  58   9      0  40       0  0.228048       0    NaN
48840  22   9      0  20       0  0.026933       0    NaN
48841  52   9  15024  40       1  0.958435    True   True

[48842 rows x 8 columns]

In [136]:
confusion_matrix = pd.crosstab(data['income'],data.pvalues)

In [137]:
confusion_matrix

pvalues      0  True
income
0        35260  1895
1         7414  4273

In [138]:
acc=(35260+4273)/(35260+1895+4273+7414)

In [139]:
acc
np.mean(data.income==data.pvalues)

0.8094058392367225